#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
DEFAULT_XCODE_PATH = Path("/Applications/Xcode.app")
XCODE_PATH_ENV = "APPLE_TEXT_XCODE_PATH"
ENABLE_APPLE_DOCS_ENV = "APPLE_TEXT_APPLE_DOCS"
ADDITIONAL_DOCS_SUBPATH = Path(
    "Contents/PlugIns/IDEIntelligenceChat.framework/Versions/A/Resources/AdditionalDocumentation"
)
DIAGNOSTICS_SUBPATH = Path(
    "Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/doc/swift/diagnostics"
)
TARGET_SKILL_NAME = "apple-text-apple-docs"
TARGET_SKILL_DIR = ROOT / "skills" / TARGET_SKILL_NAME
SYNCED_ADDITIONAL_DOCS = {
    "xcode-attributedstring-updates.md": "Foundation-AttributedString-Updates.md",
    "xcode-styled-text-editing.md": "SwiftUI-Styled-Text-Editing.md",
    "xcode-toolbar-features.md": "SwiftUI-New-Toolbar-Features.md",
}


@dataclass(frozen=True)
class XcodeDocsConfig:
    xcode_path: Path
    additional_docs_path: Path
    diagnostics_path: Path


class XcodeDocsError(RuntimeError):
    pass


def is_directory(path: Path) -> bool:
    return path.exists() and path.is_dir()


def apple_docs_enabled(env: dict[str, str] | None = None) -> bool:
    values = env or os.environ
    return values.get(ENABLE_APPLE_DOCS_ENV, "false").lower() != "false"


def resolve_xcode_path(override_path: str | None = None, env: dict[str, str] | None = None) -> Path:
    values = env or os.environ
    configured = override_path or values.get(XCODE_PATH_ENV)
    return Path(configured).expanduser() if configured else DEFAULT_XCODE_PATH


def detect_xcode(override_path: str | None = None) -> XcodeDocsConfig | None:
    xcode_path = resolve_xcode_path(override_path)
    if not is_directory(xcode_path):
        return None

    additional_docs_path = xcode_path / ADDITIONAL_DOCS_SUBPATH
    diagnostics_path = xcode_path / DIAGNOSTICS_SUBPATH
    if not is_directory(additional_docs_path) or not is_directory(diagnostics_path):
        return None

    return XcodeDocsConfig(
        xcode_path=xcode_path,
        additional_docs_path=additional_docs_path,
        diagnostics_path=diagnostics_path,
    )


def require_xcode(override_path: str | None = None) -> XcodeDocsConfig:
    config = detect_xcode(override_path)
    if config is None:
        raise XcodeDocsError(
            "Xcode documentation not found. Pass --xcode-path if Xcode is installed somewhere else."
        )
    return config


def list_markdown_files(directory: Path) -> list[Path]:
    return sorted(path for path in directory.glob("*.md") if path.is_file())


def resolve_doc_path(directory: Path, name: str) -> Path:
    normalized = name if name.endswith(".md") else f"{name}.md"
    exact = directory / normalized
    if exact.exists():
        return exact

    matches = sorted(path for path in directory.glob("*.md") if path.stem == Path(name).stem)
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        raise XcodeDocsError(f"Multiple matches found for '{name}' in {directory}")
    raise XcodeDocsError(f"Document not found: {name}")


def generated_header(source_path: Path, xcode_root: Path) -> str:
    return (
        "<!-- This file is auto-generated by internal repo tooling from the local Xcode install. -->\n\n"
        f"Source: `{source_path}`\n\n"
        f"Xcode root: `{xcode_root}`\n\n"
    )


def sync_additional_docs(config: XcodeDocsConfig, root: Path) -> list[Path]:
    target_dir = root / "skills" / TARGET_SKILL_NAME
    target_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for target_name, source_name in SYNCED_ADDITIONAL_DOCS.items():
        source_path = config.additional_docs_path / source_name
        if not source_path.exists():
            raise XcodeDocsError(f"Missing Xcode AdditionalDocumentation file: {source_name}")

        target_path = target_dir / target_name
        body = source_path.read_text(encoding="utf-8")
        target_path.write_text(
            generated_header(source_path, config.xcode_path) + body,
            encoding="utf-8",
        )
        written.append(target_path)

    index_path = target_dir / "xcode-docs-index.md"
    diagnostics = list_markdown_files(config.diagnostics_path)
    doc_lines = [
        "<!-- This file is auto-generated by internal repo tooling. -->",
        "",
        "# Apple Documentation Access Index",
        "",
        "This skill keeps a small Apple-text-focused subset of the markdown Apple bundles inside Xcode available as local reference material.",
        "",
        "## Local Apple Guides",
        "",
    ]
    for target_name, source_name in SYNCED_ADDITIONAL_DOCS.items():
        doc_lines.append(f"- [`{target_name}`]({target_name}) ← `{source_name}`")

    doc_lines.extend(
        [
            "",
            "## Runtime Context",
            "",
            "When the current client exposes Xcode-backed Apple docs or Xcode MCP resources, search those first. These checked-in files are the repo-backed fallback and reference subset.",
            "",
            "## Swift Diagnostics Bundled In Xcode",
            "",
        ]
    )
    for diagnostic in diagnostics:
        doc_lines.append(f"- `{diagnostic.name}`")
    doc_lines.append("")
    index_path.write_text("\n".join(doc_lines), encoding="utf-8")
    written.append(index_path)
    return written


def session_context_message(override_path: str | None = None, env: dict[str, str] | None = None) -> str:
    values = env or os.environ
    if not apple_docs_enabled(values):
        return (
            "Apple Docs: disabled via APPLE_TEXT_APPLE_DOCS=false. "
            "Use `apple-text-apple-docs` with repo-backed Apple references only."
        )

    config = detect_xcode(override_path or values.get(XCODE_PATH_ENV))
    if config is None:
        return (
            "Apple Docs: Xcode not detected. "
            "Use `apple-text-apple-docs` with the repo-backed Apple doc subset."
        )

    guide_count = len(list_markdown_files(config.additional_docs_path))
    diagnostic_count = len(list_markdown_files(config.diagnostics_path))
    return (
        f"Apple Docs: Xcode detected with {guide_count} guides and {diagnostic_count} Swift diagnostics. "
        "Prefer Xcode/MCP-backed Apple docs when available, then route through `apple-text-apple-docs`."
    )


def command_detect(args: argparse.Namespace) -> int:
    config = detect_xcode(args.xcode_path)
    if config is None:
        print("Xcode docs not found.")
        return 1

    print(f"Xcode: {config.xcode_path}")
    print(f"AdditionalDocumentation: {config.additional_docs_path}")
    print(f"Swift diagnostics: {config.diagnostics_path}")
    return 0


def command_list(args: argparse.Namespace) -> int:
    config = require_xcode(args.xcode_path)
    directory = config.diagnostics_path if args.diagnostic else config.additional_docs_path
    for path in list_markdown_files(directory):
        print(path.name)
    return 0


def command_read(args: argparse.Namespace) -> int:
    config = require_xcode(args.xcode_path)
    directory = config.diagnostics_path if args.diagnostic else config.additional_docs_path
    path = resolve_doc_path(directory, args.name)
    sys.stdout.write(path.read_text(encoding="utf-8"))
    return 0


def command_sync(args: argparse.Namespace) -> int:
    config = require_xcode(args.xcode_path)
    root = Path(args.root).resolve()
    written = sync_additional_docs(config, root)
    for path in written:
        print(f"Updated {path.relative_to(root).as_posix()}")
    return 0


def command_session_context(args: argparse.Namespace) -> int:
    print(session_context_message(args.xcode_path))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Inspect and sync Apple markdown documentation bundled inside Xcode."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    detect_parser = subparsers.add_parser("detect", help="Show the detected Xcode documentation paths")
    detect_parser.add_argument("--xcode-path", help="Override Xcode.app path")
    detect_parser.set_defaults(func=command_detect)

    list_parser = subparsers.add_parser("list", help="List bundled Xcode markdown files")
    list_parser.add_argument("--xcode-path", help="Override Xcode.app path")
    list_parser.add_argument(
        "--diagnostic",
        action="store_true",
        help="List Swift compiler diagnostics instead of AdditionalDocumentation guides",
    )
    list_parser.set_defaults(func=command_list)

    read_parser = subparsers.add_parser("read", help="Print a bundled Xcode markdown file to stdout")
    read_parser.add_argument("name", help="Filename or stem")
    read_parser.add_argument("--xcode-path", help="Override Xcode.app path")
    read_parser.add_argument(
        "--diagnostic",
        action="store_true",
        help="Read from the Swift diagnostics directory instead of AdditionalDocumentation",
    )
    read_parser.set_defaults(func=command_read)

    sync_parser = subparsers.add_parser(
        "sync",
        help="Sync the curated Apple-text documentation subset into skills/apple-text-apple-docs/",
    )
    sync_parser.add_argument("--xcode-path", help="Override Xcode.app path")
    sync_parser.add_argument("--root", default=str(ROOT), help="Repository root (default: current repo)")
    sync_parser.set_defaults(func=command_sync)

    context_parser = subparsers.add_parser(
        "session-context",
        help="Print a short startup message about Apple docs availability for the current environment",
    )
    context_parser.add_argument("--xcode-path", help="Override Xcode.app path")
    context_parser.set_defaults(func=command_session_context)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return args.func(args)
    except XcodeDocsError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except BrokenPipeError:
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
