#!/usr/bin/env python3

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


ROOT = Path(__file__).resolve().parent.parent
KIND_SPECS_PATH = ROOT / "config" / "skill-kinds.json"
GENERATED_NOTICE = (
    "<!-- This file is auto-generated by scripts/generate_docs.py. "
    "Edit the generator, not this file. -->"
)
PROMINENT_ENTRYPOINT_PRIORITY = 2
KIND_SPECS = json.loads(KIND_SPECS_PATH.read_text(encoding="utf-8"))
KIND_ORDER = tuple(spec["key"] for spec in KIND_SPECS)
KIND_TITLES = {spec["key"]: spec["title"] for spec in KIND_SPECS}
KIND_DESCRIPTIONS = {spec["key"]: spec["description"] for spec in KIND_SPECS}
KIND_BADGE_VARIANTS = {spec["key"]: spec["badge_variant"] for spec in KIND_SPECS}
ENTRYPOINT_ROLE_BLURBS = {
    "router": "Best when the request is broad and the right specialist is not obvious yet.",
    "workflow": "Best when the user wants a guided scan or implementation flow.",
    "diag": "Best when something is broken and symptoms are the starting point.",
    "decision": "Best when the main task is choosing the right API, view, or architecture.",
    "ref": "Best when the subsystem is already known and the user needs mechanics or API detail.",
}


def load_json(path: Path) -> Dict:
    return json.loads(path.read_text(encoding="utf-8"))


def discover_sidecars(skill_dir: Path) -> List[str]:
    return sorted(path.name for path in skill_dir.glob("*.md") if path.name != "SKILL.md")


def parse_front_matter(path: Path) -> Dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise RuntimeError(f"{path} is missing opening front matter delimiter")

    try:
        _, front_matter, _ = text.split("---\n", 2)
    except ValueError as exc:
        raise RuntimeError(f"{path} is missing closing front matter delimiter") from exc

    data: Dict[str, str] = {}
    current_key: Optional[str] = None
    block_lines: List[str] = []

    for raw_line in front_matter.splitlines():
        if current_key is not None:
            if raw_line.startswith("  ") or raw_line == "":
                block_lines.append(raw_line[2:] if raw_line.startswith("  ") else "")
                continue
            data[current_key] = "\n".join(block_lines).strip()
            current_key = None
            block_lines = []

        if not raw_line.strip():
            continue

        if ":" not in raw_line:
            raise RuntimeError(f"{path} has malformed front matter line: {raw_line}")

        key, value = raw_line.split(":", 1)
        key = key.strip()
        value = value.strip()

        if value in {"|", ""}:
            current_key = key
            block_lines = []
        else:
            data[key] = value

    if current_key is not None:
        data[current_key] = "\n".join(block_lines).strip()

    return data


def split_document(path: Path) -> Tuple[Dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    metadata = parse_front_matter(path)
    _, _, body = text.split("---\n", 2)
    return metadata, body.strip()


def sentence(text: str) -> str:
    cleaned = " ".join(text.split())
    return cleaned if cleaned.endswith(".") else cleaned + "."


def summarize_description(text: str) -> str:
    first_paragraph = text.strip().split("\n\n", 1)[0]
    return sentence(first_paragraph)


def table_description(text: str) -> str:
    """Shorter description for table cells — text before em dash."""
    if " \u2014 " in text:
        return text.split(" \u2014 ", 1)[0] + "."
    return text


def strip_sidecar_links(body: str) -> str:
    """Convert sidecar file markdown links to inline code references.

    SKILL.md bodies link sidecars as [file.md](file.md). When rendered
    inline in a docs page the target does not exist, so replace with `file.md`.
    """
    return re.sub(r"\[([a-z][a-z0-9-]*\.md)\]\(\1\)", r"`\1`", body)


def mdx_escape_body(body: str) -> str:
    """Escape generic type brackets (e.g. Range<String.Index>) in prose for MDX.

    MDX treats bare <Uppercase...> as JSX tags. This escapes those
    occurrences outside of fenced code blocks and inline code spans.
    """
    lines = body.split("\n")
    result = []
    in_fence = False

    for line in lines:
        if line.strip().startswith("```"):
            in_fence = not in_fence
            result.append(line)
            continue

        if in_fence:
            result.append(line)
            continue

        # Split by inline code spans to avoid escaping inside backticks
        parts = re.split(r"(`[^`]*`)", line)
        escaped = []
        for part in parts:
            if part.startswith("`") and part.endswith("`") and len(part) > 1:
                escaped.append(part)
            else:
                escaped.append(re.sub(r"<(?=[A-Z])", r"&lt;", part))
        result.append("".join(escaped))

    return "\n".join(result)


def body_without_leading_h1(body: str) -> str:
    """Remove leading H1 and trailing '## Related Skills' section.

    The H1 duplicates the page title and the trailing related-skills
    section is replaced by auto-generated links from catalog.json.
    """
    lines = body.split("\n")
    if lines and lines[0].startswith("# "):
        lines = lines[1:]

    # Find and remove trailing "## Related Skills" section
    cut = None
    for i, line in enumerate(lines):
        if line.strip() == "## Related Skills":
            # Only cut if there are no further H2 sections after this one
            has_later_h2 = any(
                ln.startswith("## ") and ln.strip() != "## Related Skills"
                for ln in lines[i + 1 :]
            )
            if not has_later_h2:
                cut = i
                break
    if cut is not None:
        lines = lines[:cut]

    return "\n".join(lines).strip()


def render_skill_table(skills: List[Dict], scope: str) -> List[str]:
    """Render skills as a two-column markdown table."""
    lines = [
        "| Skill | When to Use |",
        "|-------|-------------|",
    ]
    for skill in skills:
        link = f"[`{skill['name']}`]({skill_doc_link(skill['name'], scope)})"
        desc = table_description(skill["description"]).replace("|", "\\|")
        lines.append(f"| {link} | {desc} |")
    lines.append("")
    return lines


def display_plugin_name(plugin_name: str) -> str:
    return plugin_name.replace("-", " ").title()


def with_doc_frontmatter(
    title: str,
    body: str,
    description: Optional[str] = None,
    extra_frontmatter: Optional[List[str]] = None,
) -> str:
    lines = [
        "---",
        f"title: {json.dumps(title)}",
    ]
    if description:
        lines.append(f"description: {json.dumps(description)}")
    if extra_frontmatter:
        lines.extend(extra_frontmatter)
    lines.extend(
        [
            "---",
            "",
            body.strip(),
            "",
        ]
    )
    return "\n".join(lines)


def load_skill_entries(root: Path) -> List[Dict]:
    catalog = load_json(root / "skills" / "catalog.json")
    skills = []
    for entry in catalog["skills"]:
        skill_path = root / "skills" / entry["name"] / "SKILL.md"
        metadata, body = split_document(skill_path)
        merged = dict(entry)
        merged["sidecars"] = discover_sidecars(skill_path.parent)
        merged["description"] = summarize_description(metadata["description"])
        merged["full_description"] = sentence(metadata["description"])
        merged["license"] = metadata["license"]
        merged["path"] = skill_path
        merged["body"] = body
        merged["source"] = skill_path.read_text(encoding="utf-8").rstrip()
        skills.append(merged)
    return skills


def load_commands(root: Path, plugin_name: str) -> List[Dict]:
    commands = []
    for path in sorted((root / "commands").glob("*.md")):
        metadata = parse_front_matter(path)
        commands.append(
            {
                "name": f"{plugin_name}:{path.stem}",
                "description": summarize_description(metadata["description"]),
                "path": path,
            }
        )
    return commands


def load_agents(root: Path) -> List[Dict]:
    agents = []
    for path in sorted((root / "agents").glob("*.md")):
        metadata = parse_front_matter(path)
        agents.append(
            {
                "name": metadata["name"],
                "description": summarize_description(metadata["description"]),
                "path": path,
            }
        )
    return agents


def prominent_skills(skills: List[Dict]) -> List[Dict]:
    return sorted(
        [skill for skill in skills if skill["entrypoint_priority"] <= PROMINENT_ENTRYPOINT_PRIORITY],
        key=lambda skill: (skill["entrypoint_priority"], skill["name"]),
    )


def grouped_skills(skills: List[Dict]) -> List[Tuple[str, List[Dict]]]:
    groups = []
    for kind in KIND_ORDER:
        members = sorted(
            [skill for skill in skills if skill["kind"] == kind],
            key=lambda skill: (skill["entrypoint_priority"], skill["name"]),
        )
        groups.append((kind, members))
    return groups


def entrypoint_summary(skill: Dict) -> str:
    return table_description(skill["description"])


def role_anchor(kind: str) -> str:
    return KIND_TITLES[kind].lower().replace(" ", "-")


def specialist_entry_skills(skills: List[Dict]) -> List[Dict]:
    return sorted(
        [
            skill
            for skill in skills
            if skill["entrypoint_priority"] == PROMINENT_ENTRYPOINT_PRIORITY + 1
            and skill["kind"] in {"workflow", "diag", "decision"}
        ],
        key=lambda skill: (skill["kind"], skill["name"]),
    )


def top_decision_skills(skills: List[Dict], limit: int = 3) -> List[Dict]:
    decisions = sorted(
        [
            skill
            for skill in skills
            if skill["kind"] == "decision" and skill["entrypoint_priority"] <= PROMINENT_ENTRYPOINT_PRIORITY + 1
        ],
        key=lambda skill: (skill["entrypoint_priority"], skill["name"]),
    )
    return decisions[:limit]


def find_skill(skills: List[Dict], name: str) -> Optional[Dict]:
    for skill in skills:
        if skill["name"] == name:
            return skill
    return None


def top_skill_of_kind(skills: List[Dict], kind: str) -> Optional[Dict]:
    matches = [skill for skill in skills if skill["kind"] == kind]
    if not matches:
        return None
    return sorted(matches, key=lambda skill: (skill["entrypoint_priority"], skill["name"]))[0]


def skill_doc_link(skill_name: str, scope: str) -> str:
    if scope not in {"root", "skills", "guide", "skill"}:
        raise ValueError("Unknown scope: " + scope)
    return f"/skills/{skill_name}/"


def docs_page_link(route: str, scope: str) -> str:
    prefixes = {
        "root": "",
        "skills": "",
        "guide": "guide/",
    }
    if scope not in prefixes:
        raise ValueError("Unknown scope: " + scope)
    return f"/{prefixes[scope]}{route.strip('/')}/"


def linked_skill_line(skill: Dict, scope: str) -> str:
    return f"- [`{skill['name']}`]({skill_doc_link(skill['name'], scope)}): {skill['description']}"


def render_skill_list(skills: List[Dict], scope: str) -> List[str]:
    lines = [linked_skill_line(skill, scope) for skill in skills]
    lines.append("")
    return lines


def render_code_component(source_var: str, language: str, title: str) -> str:
    return f'<Code code={{{source_var}}} lang={{{json.dumps(language)}}} title={{{json.dumps(title)}}} />'


def render_linkcard_grid_mdx(cards: List[Tuple[str, str]], stagger: bool = False) -> List[str]:
    opening = "<CardGrid stagger={true}>" if stagger else "<CardGrid>"
    lines = [opening, ""]

    for title, href in cards:
        lines.append(f"  <LinkCard title={json.dumps(title)} href={json.dumps(href)} />")
        lines.append("")

    lines.extend(
        [
            "</CardGrid>",
            "",
        ]
    )
    return lines


def render_readme(plugin: Dict, marketplace: Dict, skills: List[Dict], commands: List[Dict], agents: List[Dict]) -> str:
    plugin_title = display_plugin_name(plugin["name"])
    owner = marketplace["owner"]["name"]
    marketplace_name = marketplace["name"]
    command_name = commands[0]["name"] if commands else f"{plugin['name']}:ask"

    lines = [
        f"# {plugin_title}",
        "",
        GENERATED_NOTICE,
        "",
        "Deep text-system expertise for AI coding assistants. Covers TextKit 1 and 2, UITextView, NSTextView, attributed strings, text input, Core Text, Writing Tools, and everything in between.",
        "",
        "## What is Apple Text?",
        "",
        "Apple Text gives AI coding assistants deep knowledge of Apple's text rendering and editing stack — the kind that prevents TextKit 1 fallback from silently killing your Writing Tools integration, catches `String.count` vs `NSString.length` bugs in your `NSTextStorage` subclass, and knows which 10 attributes SwiftUI `Text` actually renders out of the 30+ that autocomplete suggests.",
        "",
        f"- **{len(skills)} focused text skills** covering TextKit, views, formatting, storage, input, layout, accessibility, and more",
        f"- **{len(agents)} agent** for autonomous code auditing (fallback triggers, editing lifecycle bugs, deprecated APIs)",
        f"- **{len(commands)} command** for plain-language text questions",
        "",
        "## Installation",
        "",
        "### Claude Code (native plugin)",
        "",
        "```bash",
        f"/plugin marketplace add {owner}/{plugin['name']}",
        "```",
        "",
        "Then search for \"apple-text\" in the `/plugin` menu and install.",
        "",
        "## Getting Started",
        "",
        "Skills activate automatically based on your questions. Just ask:",
        "",
        "```",
        '"My UITextView fell back to TextKit 1"',
        '"Which text view should I use?"',
        '"How do I wrap UITextView in SwiftUI?"',
        '"Audit this editor for anti-patterns"',
        '"How do I use TextEditor with AttributedString in iOS 26?"',
        "```",
        "",
        "Or use the command directly:",
        "",
        "```",
        f"/{command_name} your question here",
        "```",
        "",
        "## Key Skills",
        "",
    ]

    featured = prominent_skills(skills)
    for skill in featured:
        lines.append(f"- **`/skill {skill['name']}`** — {entrypoint_summary(skill)}")

    lines.extend([
        "",
        "## Documentation",
        "",
        f"Full documentation, skill catalog, and guides at [{owner}.github.io/{plugin['name']}](https://{owner}.github.io/{plugin['name']}/).",
        "",
    ])
    return "\n".join(lines)


def render_home(plugin: Dict, marketplace: Dict, skills: List[Dict], commands: List[Dict], agents: List[Dict]) -> str:
    plugin_title = display_plugin_name(plugin["name"])
    owner = marketplace["owner"]["name"]
    marketplace_name = marketplace["name"]
    command_name = commands[0]["name"] if commands else f"{plugin['name']}:ask"
    featured = prominent_skills(skills)
    audit_skill = top_skill_of_kind(skills, "workflow")

    lines = [
        'import { CardGrid, LinkCard } from "@astrojs/starlight/components";',
        "",
        "{/* This file is auto-generated by scripts/generate_docs.py. Edit the generator, not this file. */}",
        "",
        f"Use this page when you are new to {plugin_title} or need the fastest route into the docs.",
        "",
        f"{plugin_title} keeps Apple text-system docs small and predictable: plain setup, clear routing, and generated pages for every skill.",
        "",
        "It covers Apple-platform text views, TextKit, attributed text, layout invalidation, editor behavior, and Writing Tools without collapsing into generic SwiftUI guidance.",
        "",
        "## Quick Start",
        "",
        "### Install the plugin",
        "",
        "```bash",
        f"/plugin marketplace add {owner}/{plugin['name']}",
        f"/plugin install {plugin['name']}@{marketplace_name}",
        "```",
        "",
        f"Or install individual skills with [openskills](https://github.com/numman-ali/openskills):",
        "",
        "```bash",
        f"npx openskills install {owner}/{plugin['name']} --skill text-views",
        "```",
        "",
        f"Package surface: {len(skills)} skills, {len(commands)} command{'s' if len(commands) != 1 else ''}, {len(agents)} agent{'s' if len(agents) != 1 else ''}.",
        "",
        "## Start With The Right Surface",
        "",
        f"- Plain-language question: start with `/{command_name}`.",
        f"- Known subsystem or API family: go straight to [Skills]({docs_page_link('skills', 'root')}).",
    ]
    if audit_skill is not None:
        lines.extend(
            [
                f"- Findings-first code review: start with [`{audit_skill['name']}`]({skill_doc_link(audit_skill['name'], 'root')}) or [Agents]({docs_page_link('agents', 'root')}).",
                "",
            ]
        )
    lines.extend(
        [
        "## Start Here",
        "",
        ]
    )
    lines.extend(
        render_linkcard_grid_mdx(
            [
                ("Setup", docs_page_link("setup", "root")),
                ("Skills", docs_page_link("skills", "root")),
                ("Commands", docs_page_link("commands", "root")),
                ("Agents", docs_page_link("agents", "root")),
                ("Example Conversations", docs_page_link("example-conversations", "root")),
                ("Guide", docs_page_link("guide", "root")),
            ],
            stagger=True,
        )
    )
    lines.extend(
        [
            "## Core Entry Points",
            "",
        ]
    )

    lines.extend(render_linkcard_grid_mdx([(skill["name"], skill_doc_link(skill["name"], "root")) for skill in featured]))
    lines.extend(render_skill_list(featured, "root"))
    lines.extend(
        [
            "## Why This Exists",
            "",
            "Apple text-system work often gets flattened into generic SwiftUI advice. These docs keep TextKit, UIKit/AppKit text views, attributed text, layout invalidation, viewport rendering, and Writing Tools explicit.",
            "",
        ]
    )
    return "\n".join(lines)


def render_setup_page(marketplace: Dict, plugin: Dict, commands: List[Dict], agents: List[Dict]) -> str:
    owner = marketplace["owner"]["name"]
    marketplace_name = marketplace["name"]
    command_name = commands[0]["name"] if commands else f"{plugin['name']}:ask"
    agent_note = agents[0]["name"] if agents else "the bundled specialist agent"

    lines = [
        GENERATED_NOTICE,
        "",
        "Use this page when you are deciding how much of Apple Text to install.",
        "",
        "## Install Everything",
        "",
        "```bash",
        f"/plugin marketplace add {owner}/{plugin['name']}",
        f"/plugin install {plugin['name']}@{marketplace_name}",
        "```",
        "",
        f"After install, start with `/{command_name}`.",
        "",
        "Pick this path when you want the router, the generated docs, and the full skill catalog available immediately.",
        "",
        "## Install Individual Skills",
        "",
        f"Pick only the skills you need with [openskills](https://github.com/numman-ali/openskills):",
        "",
        "```bash",
        f"npx openskills install {owner}/{plugin['name']} --skill text-views",
        "```",
        "",
        "Each skill page shows the exact command to install it.",
        "",
        "Pick this path when you already know the subsystem and want a smaller local surface.",
        "",
        "## What You Get",
        "",
        f"- **{len(commands)} command{'s' if len(commands) != 1 else ''}**: `/{command_name}` for plain-language questions.",
        f"- **{len(agents)} agent{'s' if len(agents) != 1 else ''}**: `{agent_note}` runs focused TextKit audits.",
        f"- **Skills**: browse the [full catalog]({docs_page_link('skills', 'root')}) or start from [problem routing]({docs_page_link('guide/problem-routing', 'root')}).",
        "",
        "## Read Next",
        "",
        f"- [Skills]({docs_page_link('skills', 'root')})",
        f"- [Commands]({docs_page_link('commands', 'root')})",
        f"- [Agents]({docs_page_link('agents', 'root')})",
        f"- [Problem Routing]({docs_page_link('guide/problem-routing', 'root')})",
        "",
    ]
    return "\n".join(lines)


def render_skills_overview(skills: List[Dict], commands: List[Dict]) -> str:
    featured = prominent_skills(skills)
    groups = grouped_skills(skills)
    command_name = commands[0]["name"] if commands else "apple-text:ask"

    lines = [
        'import { CardGrid, LinkCard } from "@astrojs/starlight/components";',
        "",
        "{/* This file is auto-generated by scripts/generate_docs.py. Edit the generator, not this file. */}",
        "",
        f"Apple Text ships {len(skills)} skills. This page is the canonical grouped catalog: start with the front doors, then scan the role that matches the job.",
        "",
        "## Start Here",
        "",
        f"If the user does not know the catalog yet, start with `/{command_name}`.",
        "",
    ]
    lines.extend(
        render_linkcard_grid_mdx(
            [(skill["name"], skill_doc_link(skill["name"], "skills")) for skill in featured],
            stagger=True,
        )
    )

    lines.extend(
        [
            "## Browse By Role",
            "",
            "These sections follow a role-based scan pattern: broad intake first, then workflows, diagnostics, decisions, and references.",
            "",
        ]
    )
    lines.extend(
        render_linkcard_grid_mdx(
            [
                (f"{KIND_TITLES[kind]} ({len(members)})", f"#{role_anchor(kind)}")
                for kind, members in groups
            ]
        )
    )
    for kind, members in groups:
        lines.extend(
            [
                f"## {KIND_TITLES[kind]}",
                "",
                KIND_DESCRIPTIONS[kind],
                "",
            ]
        )
        lines.extend(render_skill_table(members, "skills"))

    lines.extend(
        [
            "## Read Next",
            "",
        ]
    )
    lines.extend(
        render_linkcard_grid_mdx(
            [
                ("Problem Routing", docs_page_link("guide/problem-routing", "skills")),
                ("Entry Points", docs_page_link("guide/entry-points", "skills")),
                ("Example Conversations", docs_page_link("example-conversations", "skills")),
            ]
        )
    )
    return "\n".join(lines)


def render_commands_page(root: Path, commands: List[Dict], skills: List[Dict]) -> str:
    router_skill = top_skill_of_kind(skills, "router")
    workflow_skill = top_skill_of_kind(skills, "workflow")
    diagnostic_skill = top_skill_of_kind(skills, "diag")
    decision_skill = top_skill_of_kind(skills, "decision")

    lines = [
        GENERATED_NOTICE,
        "",
        "Use this page when you want the plugin to choose the first skill for you.",
        "",
        "Apple Text keeps this surface intentionally small: one broad intake command, then skill routing for the rest.",
        "",
        "## Start Here",
        "",
    ]

    for command in commands:
        lines.extend(
            [
                f"### `{command['name']}`",
                "",
                command["description"],
                "",
                "Best used for:",
                "",
                "- broad Apple text questions",
                "- first-contact prompts that mention symptoms instead of APIs",
                "- mixed requests where routing matters more than memorizing the catalog",
                "",
                "Example prompts:",
                "",
                '- "Why did my UITextView fall back to TextKit 1?"',
                '- "Review this editor code for TextKit problems."',
                '- "Should this screen use TextEditor or UITextView?"',
                "",
                "What happens next:",
                "",
            ]
        )
        if router_skill is not None:
            lines.append(
                f"- Broad questions usually route into [`{router_skill['name']}`]({skill_doc_link(router_skill['name'], 'root')})."
            )
        if workflow_skill is not None:
            lines.append(
                f"- Review or integration flows usually route into [`{workflow_skill['name']}`]({skill_doc_link(workflow_skill['name'], 'root')})."
            )
        if diagnostic_skill is not None:
            lines.append(
                f"- Broken behavior usually routes into [`{diagnostic_skill['name']}`]({skill_doc_link(diagnostic_skill['name'], 'root')})."
            )
        if decision_skill is not None:
            lines.append(
                f"- Tradeoff questions usually route into [`{decision_skill['name']}`]({skill_doc_link(decision_skill['name'], 'root')})."
            )
        lines.extend(
            [
                "",
                f"Source: `{command['path'].relative_to(root).as_posix()}`.",
                "",
            ]
        )

    lines.extend(
        [
            "## Read Next",
            "",
            f"- [Agents]({docs_page_link('agents', 'root')})",
            f"- [Skills]({docs_page_link('skills', 'root')})",
            f"- [Commands And Agents Guide]({docs_page_link('guide/commands-and-agents', 'root')})",
            "",
        ]
    )
    return "\n".join(lines)


def render_agents_page(root: Path, agents: List[Dict], skills: List[Dict]) -> str:
    audit_skill = find_skill(skills, "text-audit")

    lines = [
        GENERATED_NOTICE,
        "",
        "Use this page when the right move is a specialist scan over real code, not a general explanation.",
        "",
        f"Apple Text currently ships {len(agents)} agent{'s' if len(agents) != 1 else ''}.",
        "",
        "## Agents",
        "",
    ]

    for agent in agents:
        lines.extend(
            [
                f"### `{agent['name']}`",
                "",
                agent["description"],
                "",
                "Best used for:",
                "",
                "- findings-first reviews of editor code",
                "- scanning a codebase for TextKit anti-patterns",
                "- focused audits where file references and fix directions matter",
                "",
                "You get:",
                "",
                "- findings grouped by severity",
                "- file references for each issue",
                "- one concrete fix direction per finding",
                "",
                f"Source: `{agent['path'].relative_to(root).as_posix()}`.",
                "",
            ]
        )
    if audit_skill is not None:
        lines.extend(
            [
                "## Start Here If The User Just Asked For A Review",
                "",
                f"Use [`{audit_skill['name']}`]({skill_doc_link(audit_skill['name'], 'root')}) when the user asks for an audit in natural language and does not need to think about agents explicitly.",
                "",
            ]
        )

    lines.extend(
        [
            "## Read Next",
            "",
            f"- [Commands]({docs_page_link('commands', 'root')})",
            f"- [Skills]({docs_page_link('skills', 'root')})",
            f"- [Commands And Agents Guide]({docs_page_link('guide/commands-and-agents', 'root')})",
            "",
        ]
    )
    return "\n".join(lines)


def render_guide_index(skills: List[Dict]) -> str:
    skill_names = {skill["name"] for skill in skills}
    choice_names = [skill["name"] for skill in top_decision_skills(skills)]
    if "apple-text" in skill_names:
        broad_line = f"- Question is broad: read [Problem Routing]({docs_page_link('problem-routing', 'guide')}) or start from `/skill apple-text`."
    else:
        broad_line = f"- Question is broad: read [Problem Routing]({docs_page_link('problem-routing', 'guide')})."

    debug_targets = [name for name in ("text-textkit-diag", "text-audit") if name in skill_names]
    if len(debug_targets) == 2:
        editor_line = f"- Editor is broken: jump to `/skill {debug_targets[0]}` or `/skill {debug_targets[1]}`."
    elif len(debug_targets) == 1:
        editor_line = f"- Editor is broken: jump to `/skill {debug_targets[0]}`."
    else:
        editor_line = f"- Editor is broken: start from [Problem Routing]({docs_page_link('problem-routing', 'guide')})."

    if len(choice_names) == 1:
        choice_line = f"- You need a choice: use `{choice_names[0]}`."
    elif len(choice_names) == 2:
        choice_line = f"- You need a choice: use `{choice_names[0]}` or `{choice_names[1]}`."
    elif len(choice_names) >= 3:
        choice_line = (
            f"- You need a choice: use `{choice_names[0]}`, `{choice_names[1]}`, "
            f"or `{choice_names[2]}`."
        )
    else:
        choice_line = f"- You need a choice: start from [Problem Routing]({docs_page_link('problem-routing', 'guide')})."

    lines = [
        'import { CardGrid, LinkCard, Steps } from "@astrojs/starlight/components";',
        "",
        "{/* This file is auto-generated by scripts/generate_docs.py. Edit the generator, not this file. */}",
        "",
        "Use the guide when you need repo-level intent instead of a single command or skill page.",
        "",
        "Start here if you are new to the plugin, deciding how the docs are organized, or trying to understand which page should be the first click for a user.",
        "",
        "<Steps>",
        "",
        "1. Install the plugin.",
        "2. Start from `/apple-text:ask`, `/skill apple-text`, or the routing guide.",
        "3. Open specialist skills only when the problem is clearly scoped.",
        "",
        "</Steps>",
        "",
        "## What Makes This Plugin Different",
        "",
        "- It is intentionally narrow.",
        "- It keeps non-SwiftUI text concerns first-class.",
        "- It favors focused skills and diagnostics over giant catch-all documents.",
        "- It treats packaging quality as part of the product.",
        "",
        "## What The Guide Helps You Do",
        "",
        "- Get from install to a good first answer quickly.",
        "- Route broad questions without explaining the whole catalog.",
        "- Understand when to use commands, skills, or the agent surface.",
        "",
        "## Fast Path",
        "",
        broad_line,
        editor_line,
        choice_line,
        "",
        "## Read Next",
        "",
    ]
    lines.extend(
        render_linkcard_grid_mdx(
            [
                ("Quick Start", docs_page_link("quick-start", "guide")),
                ("Install", docs_page_link("install", "guide")),
                ("Routing Model", docs_page_link("routing-model", "guide")),
                ("Entry Points", docs_page_link("entry-points", "guide")),
                ("Problem Routing", docs_page_link("problem-routing", "guide")),
                ("Commands And Agents", docs_page_link("commands-and-agents", "guide")),
            ],
            stagger=True,
        )
    )
    return "\n".join(lines)


def render_quick_start(marketplace: Dict, plugin: Dict, skills: List[Dict], commands: List[Dict]) -> str:
    owner = marketplace["owner"]["name"]
    marketplace_name = marketplace["name"]
    command_name = commands[0]["name"] if commands else f"{plugin['name']}:ask"
    featured = prominent_skills(skills)
    router_skill = top_skill_of_kind(skills, "router")
    workflow_skill = top_skill_of_kind(skills, "workflow")
    diagnostic_skill = top_skill_of_kind(skills, "diag")
    decision_skill = top_skill_of_kind(skills, "decision")

    lines = [
        GENERATED_NOTICE,
        "",
        "Use this page when you want the shortest path from install to a good first answer.",
        "",
        "## 1. Install",
        "",
        "```bash",
        f"/plugin marketplace add {owner}/{plugin['name']}",
        f"/plugin install {plugin['name']}@{marketplace_name}",
        "```",
        "",
        "## 2. Sanity Check",
        "",
        f"- Run `/{command_name}` for a plain-language prompt.",
        f"- Open the [Skills]({docs_page_link('skills', 'root')}) page and confirm the catalog renders.",
        "- If you already know the subsystem, skip straight to the matching skill page.",
        "",
        "## 3. Use The Right Front Door",
        "",
    ]
    for skill in featured:
        lines.append(
            f"- `/skill {skill['name']}` -> [`{skill['name']}`]({skill_doc_link(skill['name'], 'guide')}): {entrypoint_summary(skill)}"
        )

    lines.extend(
        [
            "",
            "## 4. Route Typical Prompts",
            "",
        ]
    )
    if router_skill is not None:
        lines.append(
            f'- "I have an Apple text problem but I do not know the subsystem yet." -> start with [`{router_skill["name"]}`]({skill_doc_link(router_skill["name"], "guide")}) or `/{command_name}`.'
        )
    if workflow_skill is not None:
        lines.append(
            f'- "Review this editor code for risks." -> start with [`{workflow_skill["name"]}`]({skill_doc_link(workflow_skill["name"], "guide")}).'
        )
    if diagnostic_skill is not None:
        lines.append(
            f'- "My layout is stale or TextKit fell back." -> start with [`{diagnostic_skill["name"]}`]({skill_doc_link(diagnostic_skill["name"], "guide")}).'
        )
    if decision_skill is not None:
        lines.append(
            f'- "Should this use TextEditor, UITextView, or NSTextView?" -> start with [`{decision_skill["name"]}`]({skill_doc_link(decision_skill["name"], "guide")}).'
        )
    lines.extend(
        [
            "",
            "## 5. Try These Prompts",
            "",
            '- "My UITextView layout is stale after editing."',
            '- "Review this TextKit code for fallback risks."',
            '- "Should this screen use TextEditor, UITextView, or NSTextView?"',
            '- "How do I render Markdown headings and lists in Apple text views?"',
            "",
            "## What Next",
            "",
            f"- If the question is still broad, read [Routing Model]({docs_page_link('routing-model', 'guide')}).",
            f"- If you already know the answer shape, use [Problem Routing]({docs_page_link('problem-routing', 'guide')}).",
            f"- If you want the full catalog, browse [Skills]({docs_page_link('skills', 'root')}).",
            "",
        ]
    )
    return "\n".join(lines)


def render_routing_model(skills: List[Dict], commands: List[Dict]) -> str:
    command_name = commands[0]["name"] if commands else "apple-text:ask"
    skill_names = {skill["name"] for skill in skills}
    routers = [skill for skill in skills if skill["kind"] == "router"]
    workflows = [skill for skill in skills if skill["kind"] == "workflow"]
    diagnostics = [skill for skill in skills if skill["kind"] == "diag"]
    decisions = top_decision_skills(skills)
    references = [skill for skill in skills if skill["kind"] == "ref"]

    lines = [
        GENERATED_NOTICE,
        "",
        "Use this page when you are routing a prompt and want a simple decision model instead of a full catalog scan.",
        "",
        "Apple Text uses progressive disclosure: start broad, then move to the narrowest skill that matches the job.",
        "",
        "## Routing Pattern",
        "",
        f"1. Start with `/{command_name}` or a router skill.",
        "2. Decide whether the user needs a workflow, a diagnosis, a choice, or a reference.",
        "3. Open the narrowest skill that matches that answer shape.",
        "",
        "Do not memorize every skill name. Ask whether the prompt is broad, broken, comparative, or already scoped to a subsystem.",
        "",
        "## Mental Model",
        "",
    ]

    if routers:
        lines.extend(
            [
                f"- **Broad intake**: start with `/skill {routers[0]['name']}`.",
                "Use this when the problem is clearly Apple text work but still mixed or underspecified.",
            ]
        )

    if workflows:
        lines.extend(
            [
                f"- **Guided flow or review**: start with `/skill {workflows[0]['name']}`.",
                "Use this when the user wants an audit, integration walkthrough, or step-by-step implementation path.",
            ]
        )

    if diagnostics:
        lines.extend(
            [
                f"- **Broken behavior**: start with `/skill {diagnostics[0]['name']}`.",
                "Use this when the user starts with stale layout, fallback, crashes, or rendering bugs.",
            ]
        )

    if decisions:
        decision_names = ", ".join(f"`{skill['name']}`" for skill in decisions[:3])
        lines.extend(
            [
                f"- **Tradeoff question**: use {decision_names}.",
                "Use this when the main job is picking the right API, architecture, or view.",
            ]
        )

    if references:
        lines.extend(
            [
                f"- **Known API family**: go straight to `/skill {references[0]['name']}` or the matching reference skill.",
                "Use this when the user already knows the subsystem and wants mechanics, behavior, or API detail.",
            ]
        )

    lines.extend(
        [
            "",
            "## Prompt Patterns",
            "",
            '- "Why is this editor broken?" -> diagnostic skill',
            '- "Review this code for risks." -> workflow skill',
            '- "Should I use A or B?" -> decision skill',
            '- "How does this Apple text API behave?" -> reference skill',
            "",
            "## Shortcuts",
            "",
        ]
    )
    if "apple-text" in skill_names:
        lines.append("- Broad Apple text question -> [`apple-text`](/skills/apple-text/)")
    if "text-audit" in skill_names:
        lines.append("- Findings-first review -> [`text-audit`](/skills/text-audit/)")
    if "text-textkit-diag" in skill_names:
        lines.append("- Debugging a broken editor -> [`text-textkit-diag`](/skills/text-textkit-diag/)")
    if "text-views" in skill_names:
        lines.append("- Choosing among text stacks -> [`text-views`](/skills/text-views/)")
    lines.extend(
        [
            "",
            "## Read Next",
            "",
            f"- [Quick Start]({docs_page_link('quick-start', 'guide')})",
            f"- [Entry Points]({docs_page_link('entry-points', 'guide')})",
            f"- [Problem Routing]({docs_page_link('problem-routing', 'guide')})",
            "",
        ]
    )
    return "\n".join(lines)


def render_entry_points(skills: List[Dict], commands: List[Dict]) -> str:
    featured = prominent_skills(skills)
    specialists = specialist_entry_skills(skills)
    command = commands[0] if commands else None

    lines = [
        GENERATED_NOTICE,
        "",
        "These are the front doors that matter.",
        "",
        "> If you are about to explain the whole plugin taxonomy to a user, you probably chose the wrong entry point.",
        "",
    ]

    if command is not None:
        lines.extend(
            [
                f"## `/{command['name']}`",
                "",
                command["description"],
                "",
                "Good for:",
                "",
                "- plain-language prompts",
                "- first-contact questions",
                "- mixed symptoms where the right skill is not obvious yet",
                "",
            ]
        )

    lines.extend(["## Prominent Skills", ""])
    for skill in featured:
        lines.extend(
            [
                f"### [`{skill['name']}`]({skill_doc_link(skill['name'], 'guide')})",
                "",
                skill["description"],
                "",
                "Best first move:",
                "",
                f"- {ENTRYPOINT_ROLE_BLURBS.get(skill['kind'], entrypoint_summary(skill))}",
                "",
            ]
        )

    lines.extend(
        [
            "## Direct Specialist Skills",
            "",
            "These are the next stop once the request is already scoped:",
            "",
        ]
    )
    lines.extend(render_skill_list(specialists, "guide"))
    return "\n".join(lines)


def render_problem_routing(skills: List[Dict]) -> str:
    groups = grouped_skills(skills)
    featured = prominent_skills(skills)

    lines = [
        'import { CardGrid, LinkCard } from "@astrojs/starlight/components";',
        "",
        "{/* This file is auto-generated by scripts/generate_docs.py. Edit the generator, not this file. */}",
        "",
        "Use this page when you know the answer shape but not the exact skill name.",
        "",
        "The routing classes come from `skills/catalog.json`: `router`, `workflow`, `diag`, `decision`, and `ref`.",
        "",
        "## Start Here",
        "",
    ]
    lines.extend(render_skill_list(featured, "guide"))
    lines.extend(
        render_linkcard_grid_mdx(
            [
                (KIND_TITLES[kind], f"#{role_anchor(kind)}")
                for kind, members in groups
                if members
            ]
        )
    )
    lines.extend(["## Route By Answer Type", ""])

    for kind, members in groups:
        example = members[0]["name"] if members else "apple-text"
        lines.extend(
            [
                f"### {KIND_TITLES[kind]}",
                "",
                KIND_DESCRIPTIONS[kind],
                "",
                f"Example route: `/skill {example}`",
                "",
            ]
        )
        lines.extend(render_skill_list(members, "guide"))

    return "\n".join(lines)


def render_commands_and_agents(root: Path, commands: List[Dict], agents: List[Dict]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        f"{len(commands)} command, {len(agents)} agent, no clutter.",
        "",
        "Use commands when the question is still fuzzy. Use agents when the task is a specialist scan over real code.",
        "",
        "## Commands",
        "",
    ]

    for command in commands:
        lines.extend(
            [
                f"### `{command['name']}`",
                "",
                command["description"],
                "",
                f"Implementation: `{command['path'].relative_to(root).as_posix()}`.",
                "",
            ]
        )

    lines.extend(["## Agents", ""])
    for agent in agents:
        lines.extend(
            [
                f"### `{agent['name']}`",
                "",
                agent["description"],
                "",
                f"Implementation: `{agent['path'].relative_to(root).as_posix()}`.",
                "",
            ]
        )

    return "\n".join(lines)


def render_install(marketplace: Dict, plugin: Dict, agents: List[Dict]) -> str:
    owner = marketplace["owner"]["name"]
    marketplace_name = marketplace["name"]
    agent_note = agents[0]["name"] if agents else "the matching agent"

    lines = [
        GENERATED_NOTICE,
        "",
        "This guide covers the packaging choices in more detail than the setup page.",
        "",
        "## Marketplace Install",
        "",
        "```bash",
        f"/plugin marketplace add {owner}/{plugin['name']}",
        f"/plugin install {plugin['name']}@{marketplace_name}",
        "```",
        "",
        f"## Install Individual Skills",
        "",
        f"Install specific skills directly from GitHub with [openskills](https://github.com/numman-ali/openskills):",
        "",
        "```bash",
        f"npx openskills install {owner}/{plugin['name']} --skill text-views",
        "```",
        "",
        "Install multiple skills at once:",
        "",
        "```bash",
        f"npx openskills install {owner}/{plugin['name']} --skill text-views --skill text-audit",
        "```",
        "",
        "Each skill page shows the exact install command.",
        "",
    ]
    return "\n".join(lines)


def render_skill_page(skill: Dict, skills: List[Dict], owner: str, plugin_name: str) -> str:
    by_name = {entry["name"]: entry for entry in skills}
    related = [by_name[name] for name in skill.get("related_skills", []) if name in by_name]
    content = mdx_escape_body(strip_sidecar_links(body_without_leading_h1(skill["body"])))
    badge_variant = KIND_BADGE_VARIANTS.get(skill["kind"], "default")

    lines = [
        "import { Code, Badge } from '@astrojs/starlight/components';",
        "import skillSource from './SKILL-source.txt?raw';",
        "",
        "{/* This file is auto-generated by scripts/generate_docs.py. Edit the generator, not this file. */}",
        "",
        f'<Badge text="{KIND_TITLES[skill["kind"]]}" variant="{badge_variant}" />',
        "",
        skill["full_description"],
        "",
        "```bash",
        f"npx openskills install {owner}/{plugin_name} --skill {skill['name']}",
        "```",
        "",
    ]

    if content:
        lines.extend([content, ""])

    if related:
        lines.extend(
            [
                "## Related Skills",
                "",
            ]
        )
        lines.extend(render_skill_list(related, "skill"))

    if skill.get("sidecars"):
        lines.extend(
            [
                "## Sidecar Files",
                "",
            ]
        )
        for sidecar in skill["sidecars"]:
            lines.append(f"- `skills/{skill['name']}/{sidecar}`")
        lines.append("")

    lines.extend(
        [
            "<details>",
            "<summary>Full SKILL.md source</summary>",
            "",
            render_code_component("skillSource", "md", "SKILL.md"),
            "",
            "</details>",
            "",
        ]
    )
    return "\n".join(lines)


def generated_docs(root: Path) -> Dict[Path, str]:
    plugin = load_json(root / ".claude-plugin" / "plugin.json")
    marketplace = load_json(root / ".claude-plugin" / "marketplace.json")
    skills = load_skill_entries(root)
    commands = load_commands(root, plugin["name"])
    agents = load_agents(root)

    docs = {
        root / "README.md": render_readme(plugin, marketplace, skills, commands, agents),
        root / "src" / "content" / "docs" / "index.mdx": with_doc_frontmatter(
            display_plugin_name(plugin["name"]),
            render_home(plugin, marketplace, skills, commands, agents),
            "Focused docs for Apple text-system work.",
        ),
        root / "src" / "content" / "docs" / "setup.md": with_doc_frontmatter(
            "Setup",
            render_setup_page(marketplace, plugin, commands, agents),
            "Install the Apple Text plugin or individual skills.",
        ),
        root / "src" / "content" / "docs" / "skills" / "index.mdx": with_doc_frontmatter(
            "Skills",
            render_skills_overview(skills, commands),
            "Browse Apple Text skills by entry point and routing role.",
            [
                "sidebar:",
                "  order: 1",
            ],
        ),
        root / "src" / "content" / "docs" / "commands.md": with_doc_frontmatter(
            "Commands",
            render_commands_page(root, commands, skills),
            "Command overview for the Apple Text plugin.",
        ),
        root / "src" / "content" / "docs" / "agents.md": with_doc_frontmatter(
            "Agents",
            render_agents_page(root, agents, skills),
            "Agent overview for the Apple Text plugin.",
        ),
        root / "src" / "content" / "docs" / "guide" / "index.mdx": with_doc_frontmatter(
            "Overview",
            render_guide_index(skills),
            "Repo-level overview and routing guidance for the Apple Text plugin.",
            [
                "sidebar:",
                "  order: 1",
            ],
        ),
        root / "src" / "content" / "docs" / "guide" / "quick-start.md": with_doc_frontmatter(
            "Quick Start",
            render_quick_start(marketplace, plugin, skills, commands),
            extra_frontmatter=[
                "sidebar:",
                "  order: 2",
            ],
        ),
        root / "src" / "content" / "docs" / "guide" / "routing-model.md": with_doc_frontmatter(
            "Routing Model",
            render_routing_model(skills, commands),
            extra_frontmatter=[
                "sidebar:",
                "  order: 5",
            ],
        ),
        root / "src" / "content" / "docs" / "guide" / "entry-points.md": with_doc_frontmatter(
            "Entry Points",
            render_entry_points(skills, commands),
            extra_frontmatter=[
                "sidebar:",
                "  order: 4",
            ],
        ),
        root / "src" / "content" / "docs" / "guide" / "problem-routing.md": with_doc_frontmatter(
            "Problem Routing",
            render_problem_routing(skills),
            extra_frontmatter=[
                "sidebar:",
                "  order: 6",
            ],
        ),
        root / "src" / "content" / "docs" / "guide" / "commands-and-agents.md": with_doc_frontmatter(
            "Commands And Agents",
            render_commands_and_agents(root, commands, agents),
            extra_frontmatter=[
                "sidebar:",
                "  order: 7",
            ],
        ),
        root / "src" / "content" / "docs" / "guide" / "install.md": with_doc_frontmatter(
            "Install",
            render_install(marketplace, plugin, agents),
            extra_frontmatter=[
                "sidebar:",
                "  order: 3",
            ],
        ),
    }

    for skill in skills:
        docs[root / "src" / "content" / "docs" / "skills" / skill["name"] / "index.mdx"] = with_doc_frontmatter(
            skill["name"],
            render_skill_page(skill, skills, marketplace["owner"]["name"], plugin["name"]),
            skill["description"],
        )
        docs[root / "src" / "content" / "docs" / "skills" / skill["name"] / "SKILL-source.txt"] = (
            skill["source"].rstrip() + "\n"
        )

    return docs


def write_docs(root: Path) -> List[Path]:
    changed = []
    for path, content in generated_docs(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        normalized = content.rstrip() + "\n"
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != normalized:
            path.write_text(normalized, encoding="utf-8")
            changed.append(path)
    return changed


def stale_docs(root: Path) -> List[Path]:
    stale = []
    for path, content in generated_docs(root).items():
        normalized = content.rstrip() + "\n"
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        if existing != normalized:
            stale.append(path)
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Apple Text docs from package metadata.")
    parser.add_argument(
        "--root",
        default=str(ROOT),
        help="Plugin root to generate docs for (default: repository root).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether generated docs are up to date without writing changes.",
    )
    args = parser.parse_args()
    root = Path(args.root).resolve()

    if args.check:
        stale = stale_docs(root)
        if stale:
            for path in stale:
                rel = path.relative_to(root).as_posix()
                print("STALE: " + rel, file=sys.stderr)
            print("Run python3 scripts/generate_docs.py to regenerate docs.", file=sys.stderr)
            return 1
        print("Generated docs are up to date.")
        return 0

    changed = write_docs(root)
    if not changed:
        print("Generated docs are already up to date.")
        return 0

    for path in changed:
        print("Updated " + path.relative_to(root).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
